"""
PR Generator - Generates detailed pull request content.

Creates well-formatted pull request titles, descriptions,
and summaries based on migration results.
"""

from devassist.core.models import MigrationState, CodeChange


class PRGenerator:
    """
    Generates pull request content for migrations.
    
    Creates structured PR descriptions with:
    - Migration summary
    - List of changes
    - Test results
    - Before/after code samples
    """

    def generate_title(self, state: MigrationState) -> str:
        """
        Generate a pull request title.
        
        Args:
            state: Migration state
            
        Returns:
            PR title string
        """
        migration_names = {
            "py2to3": "Python 2 to 3",
            "flask_to_fastapi": "Flask to FastAPI",
        }
        
        migration_name = migration_names.get(
            state.migration_type.value, state.migration_type.value
        )
        
        return f"[DevAssist] {migration_name} Migration"

    def generate_body(self, state: MigrationState) -> str:
        """
        Generate a detailed pull request body.
        
        Args:
            state: Migration state
            
        Returns:
            PR body as Markdown string
        """
        sections = [
            self._generate_header(),
            self._generate_summary(state),
            self._generate_changes_section(state),
            self._generate_patterns_section(state),
            self._generate_test_results_section(state),
            self._generate_footer(),
        ]
        
        return "\n\n".join(section for section in sections if section)

    def _generate_header(self) -> str:
        """Generate the PR header."""
        return """## 🔄 DevAssist Automated Migration

This pull request was automatically generated by DevAssist, a multi-agent code migration tool."""

    def _generate_summary(self, state: MigrationState) -> str:
        """Generate the migration summary section."""
        summary = state.get_summary()
        
        status_emoji = "✅" if state.tests_passed else "⚠️"
        
        return f"""### Summary

| Metric | Value |
|--------|-------|
| Migration Type | `{state.migration_type.value}` |
| Files Processed | {summary['files_processed']} |
| Patterns Found | {summary['patterns_found']} |
| Changes Applied | {summary['changes_applied']} |
| Tests Passed | {status_emoji} {summary['tests_passed']} |
| Errors | {summary['errors']} |"""

    def _generate_changes_section(self, state: MigrationState) -> str:
        """Generate the changes section with code diffs."""
        if not state.applied_changes:
            return ""
        
        lines = ["### Changes Made\n"]
        
        # Group changes by file
        changes_by_file: dict[str, list[CodeChange]] = {}
        for change in state.applied_changes:
            file_key = str(change.file_path)
            if file_key not in changes_by_file:
                changes_by_file[file_key] = []
            changes_by_file[file_key].append(change)
        
        for file_path, changes in list(changes_by_file.items())[:5]:  # Limit files
            lines.append(f"\n#### `{file_path}`\n")
            
            for change in changes[:3]:  # Limit changes per file
                lines.append(f"**{change.explanation}**\n")
                lines.append("<details>")
                lines.append("<summary>View diff</summary>\n")
                lines.append("```diff")
                
                # Format original code with - prefix
                for line in change.original_code.split("\n"):
                    lines.append(f"- {line}")
                
                # Format new code with + prefix
                for line in change.new_code.split("\n"):
                    lines.append(f"+ {line}")
                
                lines.append("```")
                lines.append("</details>\n")
            
            if len(changes) > 3:
                lines.append(f"*... and {len(changes) - 3} more changes*\n")
        
        if len(changes_by_file) > 5:
            lines.append(f"\n*... and changes in {len(changes_by_file) - 5} more files*")
        
        return "\n".join(lines)

    def _generate_patterns_section(self, state: MigrationState) -> str:
        """Generate the deprecated patterns section."""
        if not state.deprecated_patterns:
            return ""
        
        lines = ["### Patterns Identified\n"]
        
        # Count patterns by type
        pattern_counts: dict[str, int] = {}
        for pattern in state.deprecated_patterns:
            pattern_type = pattern.pattern_type
            pattern_counts[pattern_type] = pattern_counts.get(pattern_type, 0) + 1
        
        lines.append("| Pattern Type | Count | Severity |")
        lines.append("|-------------|-------|----------|")
        
        # Get unique patterns with their severity
        seen_types: set[str] = set()
        for pattern in state.deprecated_patterns:
            if pattern.pattern_type not in seen_types:
                seen_types.add(pattern.pattern_type)
                severity_emoji = {
                    "error": "🔴",
                    "warning": "🟡",
                    "info": "🔵",
                }.get(pattern.severity, "⚪")
                
                lines.append(
                    f"| `{pattern.pattern_type}` | "
                    f"{pattern_counts[pattern.pattern_type]} | "
                    f"{severity_emoji} {pattern.severity} |"
                )
        
        return "\n".join(lines)

    def _generate_test_results_section(self, state: MigrationState) -> str:
        """Generate the test results section."""
        if not state.test_results:
            return "### Test Results\n\nNo automated tests were run."
        
        lines = ["### Test Results\n"]
        
        passed = sum(1 for r in state.test_results if r.passed)
        total = len(state.test_results)
        
        lines.append(f"**{passed}/{total} tests passed**\n")
        
        if passed < total:
            lines.append("#### Failed Tests\n")
            for result in state.test_results:
                if not result.passed:
                    lines.append(f"- `{result.test_name}`: {result.error_message[:100]}...")
        
        return "\n".join(lines)

    def _generate_footer(self) -> str:
        """Generate the PR footer."""
        return """---

### Next Steps

1. Review the changes above
2. Run your test suite locally
3. Check for any edge cases not covered by automated migration
4. Approve and merge when ready

---
*This PR was generated by [DevAssist](https://github.com/your-org/devassist) - Multi-Agent Code Migration Tool*"""

    def generate_commit_message(
        self, state: MigrationState, detailed: bool = False
    ) -> str:
        """
        Generate a commit message for the migration.
        
        Args:
            state: Migration state
            detailed: Whether to include detailed changes
            
        Returns:
            Commit message string
        """
        title = self.generate_title(state)
        
        if not detailed:
            return title
        
        summary = state.get_summary()
        
        body = f"""{title}

Migration Summary:
- Files processed: {summary['files_processed']}
- Patterns found: {summary['patterns_found']}
- Changes applied: {summary['changes_applied']}
- Tests passed: {summary['tests_passed']}

Generated by DevAssist"""
        
        return body
